### ISSUE TITLE
Some Orbit Graphs Discontinuous

### ISSUE THREAD

**Issue by GGillan** [gdoepp/skyreigen#1]
Hi,

Thank you for this wonderful application! :-)

I noticed something that I thought I suspect is due to the approximate nature of the orbit calculations made, but thought that I would ask. I've noticed that the orbit graph for the moon is discontinuous, with a break occurring at midnight. I have also seen this happen with the graph of at least one planet. Is this a known/understood phenomena?

It is certainly no problem for my use of the program, I just thought I would mention it in case you were unaware of it. Attached is a screen-photo showing an example of the moon's graph.

Regards,
George

![skyreigen-moon-s](https://cloud.githubusercontent.com/assets/9140259/22865738/7e32fa08-f127-11e6-8adf-43363cc17023.jpg)

**Comment by gdoepp** [comment]
Hi,

thank you for your interest in the app and for reporting this phenomenon.

The discontinuities at midnight appear when the moon and, in theory, a planet is up at 
midnight. The diagram shows the path during one calendar day. So there are two 
disconnected parts: one from midnight to set and one from rise to midnight.

The moon is further east at the end of the day just before midnight than she was at the 
beginning of the day just after midnight.

There is an issue in the app that the rise and the first hour are not shown in this case. 
That's also true for the planets. I will fix this soon. 

Regards
Gerhard

Am Sonntag, 12. Februar 2017, 21:31:35 CET schrieb GGillan:
> Hi,
> 
> Thank you for this wonderful application! :-)
> 
> I noticed something that I thought I suspect is due to the approximate
> nature of the orbit calculations made, but thought that I would ask. I've
> noticed that the orbit graph for the moon is discontinuous, with a break
> occurring at midnight. I have also seen this happen with the graph of at
> least one planet. Is this a known/understood phenomena?
> 
> It is certainly no problem for my use of the program, I just thought I would
> mention it in case you were unaware of it. Attached is a screen-photo
> showing an example of the moon's graph.
> 
> Regards,
> George
> 
> ![skyreigen-moon-s](https://cloud.githubusercontent.com/assets/9140259/22865
> 738/7e32fa08-f127-11e6-8adf-43363cc17023.jpg)

**Comment by GGillan** [comment]
Hi Gerhard,

Thank you, I'm happy my report was helpful. ☺

Regards,
George
